[workspace]
members = [
  ".",
  "jobber",
  "jobber/jobber_derive",
]

[workspace.package]
version = "0.0.0"
edition = "2021"

[features]
default = ["server"]
job_print = []
server = [
  "dep:tokio",
  "dep:axum",
  "dep:tower",
  "dep:tower-http",
  "dep:notify-debouncer-mini",
  "dep:futures-util",
  "dep:tokio-stream",
]

[package]
name = "personal_website"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
clap = { version = "4.4.6", features = ["derive"] }
serde = { version = "1.0.189", features = ["derive"] }
toml = "0.8.4"
regex = "1.10.2"

walkdir = "2.4.0"
tera = "1.19.1"
css-minify = "0.3.1"
image = "0.25.1"
markdown = "1.0.0-alpha.16"
minify-html = "0.15.0"
minify-js = { git = "https://github.com/RuairidhWilliamson/minify-js.git", rev = "bbd1fc43c8aec6e16cfd17cca276f411de23f67c" }

tokio = { version = "1.33.0", features = ["rt", "net"], optional = true }
axum = { version = "0.7.4", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5.1", features = ["fs"], optional = true }
notify-debouncer-mini = { version = "0.4.1", default-features = false, optional = true }
futures-util = { version = "0.3", optional = true }
tokio-stream = { version = "0.1.14", features = ["sync"], optional = true }

jobber = { path = "./jobber" }
