convert_images = "Webp"

[details]
name = "Ruairidh Williamson"
email = "rtaw.co.uk.impromptu302@passfwd.com"
summary = "I like to program things and this is where I document some of the things I make."

[pages]
pages = [
  "posts",
  "contact",
]

featured = [
  "clippy-lints",
  "personal-website-rs",
  "space-inserters",
]

[[pages.posts]]
slug = "clippy-lints"
[[pages.posts]]
slug = "personal-website-rs"
[[pages.posts]]
slug = "space-inserters"
[[pages.posts]]
slug = "parcel-purgatory"
[[pages.posts]]
slug = "todl"
[[pages.posts]]
slug = "boss-swap"
[[pages.posts]]
slug = "climate-crisis"
[[pages.posts]]
slug = "crossword"
[[pages.posts]]
slug = "warp-driver"
[[pages.posts]]
slug = "pseudo-haptic-drift"
[[pages.posts]]
slug = "time-terrorists"
[[pages.posts]]
slug = "trolley-folly"
[[pages.posts]]
slug = "genie-of-light"
[[pages.posts]]
slug = "personal-website"
