[package]
name = "jobber_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
syn = { version = "1.0", features = [ "full" ] }
quote = "1.0"
