on:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build rust
        run: cargo build -q --release
      - name: Build site
        run: |
          chmod +x personal_website
          ./personal_website build -r contents --minify
      - name: Auth
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud config set project $GCP_PROJECT
          echo $GCP_SA_KEY > private-key.json
          gcloud auth activate-service-account --key-file private-key.json
      - name: Upload
        run: |
          gcloud storage cp dist/* gs://rtaw.co.uk --recursive
