on:
  push:
    branches:
      - main
      - rust # testing

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build rust
        run: cargo build -q --release
      - uses: actions/upload-artifact@v3
        with:
          name: rust-bin
          path: target/release/personal_website

  build-site:
    runs-on: ubuntu-latest
    needs: build-rust
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: rust-bin
      - name: Build site
        run: |
          chmod +x personal_website
          ./personal_website build -r contents --minify
      - uses: actions/upload-artifact@v3
        with:
          name: site-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: site-dist
          path: dist
      - name: Auth
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud config set project $GCP_PROJECT
          echo $GCP_SA_KEY > private-key.json
          gcloud auth activate-service-account --key-file private-key.json
      - name: Upload
        run: |
          ls dist
          gcloud storage cp dist/* gs://preview.rtaw.co.uk --recursive
